urbanet_cv_homepage:
    pattern:  /CV
    defaults: { _controller: UrbanetCvBundle:Default:voir }
    
urbanet_cv_voir:
    pattern:  /CV/voir/{id}
    defaults: { _controller: UrbanetCvBundle:Default:voir, id: 0 }
    requirements :
      id : \d+
      
urbanet_cv_ajouter:
    pattern:  /CV/ajouter
    defaults: { _controller: UrbanetCvBundle:Default:ajouter }

urbanet_cv_editer:
    pattern:  /CV/editer/{id}
    defaults: { _controller: UrbanetCvBundle:Default:editer }

urbanet_cv_ajouter_spectacle:
    pattern:  /CV/ajouter_spectacle
    defaults: { _controller: UrbanetCvBundle:Default:ajouter_spectacle }

urbanet_cv_editer_spectacle:
    pattern:  /CV/editer_spectacle/{id}
    defaults: { _controller: UrbanetCvBundle:Default:editer_spectacle }
    requirements :
      id : \d+

urbanet_cv_supprimer_spectacle:
    pattern: /CV/supprimer_spectacle/{id}
    defaults: { _controller: UrbanetCvBundle:Default:supprimer_spectacle }
    requirements : 
      id : \d+

urbanet_cv_ajouter_formation:
    pattern: /CV/ajouter_formation
    defaults: { _controller: UrbanetCvBundle:Default:ajouter_formation }

urbanet_cv_editer_formation:
    pattern:  /CV/editer_formation/{id}
    defaults: { _controller: UrbanetCvBundle:Default:editer_formation }
    requirements :
      id : \d+

urbanet_cv_supprimer_formation:
    pattern: /CV/supprimer_formation/{id}
    defaults: { _controller: UrbanetCvBundle:Default:supprimer_formation }
    requirements : 
      id : \d+

urbanet_cv_ajouter_competence:
    pattern: /CV/ajouter_competence
    defaults: { _controller: UrbanetCvBundle:Default:ajouter_competence }

urbanet_cv_editer_competence:
    pattern:  /CV/editer_competence/{id}
    defaults: { _controller: UrbanetCvBundle:Default:editer_competence }
    requirements :
      id : \d+

urbanet_cv_supprimer_competence:
    pattern: /CV/supprimer_competence/{id}
    defaults: { _controller: UrbanetCvBundle:Default:supprimer_competence }
    requirements : 
      id : \d+